In [44]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import joblib

plt.style.use("fivethirtyeight")

In [6]:
!pip install joblib

In [59]:
#main
class perceptron:
    
    def __init__(self,eta: float=None,epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs,weights)
        
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self,x,y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x,-np.ones((len(self.x), 1))]
        print(f"x with bias :\n{x_with_bias}")
        
        for epoch in range(self.epochs):
            print('--'*10)
            print(f"for epoch >> {epoch + 1}")
            print('--'*10)
            z = self._z_outcome(x_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after the forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error : \n{self.error}")
    
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, self.error)
            print(f"updated weight after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"$$"*10)
            
            
    def predict(self,x):
        x_with_bias = np.c_[x,-np.ones((len(x), 1))]
        z = self._z_outcome(x_with_bias, self.weights)
        return self.activation_function(z)
        

In [60]:
#main
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,1,1,1]
}
df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [61]:
#main
def prepare_data(df, target_col="y"):
    x = df.drop(target_col,axis=1)
    y = df[target_col]
    return x, y

In [62]:
#main
x, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(x,y)

x with bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after the forward pass: 
[1 1 1 0]
error : 
0   -1
1    0
2    0
3    1
Name: y, dtype: int64
updated weight after epoch: 1/10: 
[ 9.99290022e-02  9.99839380e-02 -7.52435544e-05]
$$$$$$$$$$$$$$$$$$$$
--------------------
for epoch >> 2
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weight after epoch: 2/10: 
[0.099929   0.09998394 0.09992476]
$$$$$$$$$$$$$$$$$$$$
--------------------
for epoch >> 3
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error : 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weight after epoch: 3/10: 
[0.099929   0.09998394 0.09992476]
$$$$$$$$$$$$$$$$$$$$
--------------------
for epoch >> 4
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error : 
0    0
1    0
2    

In [56]:
#predict_method


# bits and pieces of the above code

In [58]:
model_or.predict(x=[[1,0]]) #OR gate

array([1])

In [28]:
onj = perceptron(eta=0.01,epochs=10)

In [29]:
onj.eta 

0.01

In [31]:
onj.epochs, onj.weights

(10, array([ 0.00015503,  0.00010663, -0.00012716]))

In [7]:
np.random.randn(3)

array([1.34070028, 0.20639187, 0.46149743])

In [24]:
-np.ones((4, 1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [23]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
y = np.ones((4,1))

In [25]:
np.c_[x,-np.ones((4, 1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [33]:
onj.fit(x,y)

x with bias :
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [40]:
z = 5
np.where(z>0, 1, 0)

array(1)

In [43]:
print("training:'forward + backword' , prediction: 'only forward'")

training:'forward + backword' , prediction: 'only forward'


In [47]:
x, y = prepare_data(df_OR)

In [48]:
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [49]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64