In [5]:
import os
import matplotlib.pyplot as plt
import pandas 
import numpy as np
import joblib

plt.style.use("fivethirtyeight")

In [6]:
!pip install joblib

In [27]:
class perceptron:
    
    def __init__(self,eta: float=None,epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def fit(self,x,y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x,-np.ones((len(self.x), 1))]
        print(f"x with bias :\n{x_with_bias}")
        

In [28]:
onj = perceptron(eta=0.01,epochs=10)

In [29]:
onj.eta 

0.01

In [31]:
onj.epochs, onj.weights

(10, array([ 0.00015503,  0.00010663, -0.00012716]))

In [7]:
np.random.randn(3)

array([1.34070028, 0.20639187, 0.46149743])

In [24]:
-np.ones((4, 1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [23]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
y = np.ones((4,1))

In [25]:
np.c_[x,-np.ones((4, 1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])